<!-- The header containing the logo -->
<header class="container_12">
    <!-- Your logos -->
    <?= Load::lib("html"); ?>
    <?= Html::link("mango/index", Html::imagen("logo.png","Mango",191,60)) ?>
    <?= Html::link("mango/index",Html::imagen("logo-mobile.png","Mango",22,70),"class: phone-title") ?>

    <div class="buttons">
        <?= Html::link("mango/index", '<span class="icon icon-sitemap"></span> Statistics </a>') ?>
        <?= Html::link("mango/index", '<span class="icon icon-list-alt"></span> Forms </a>') ?>
        <?= Html::link("mango/index", '<span class="icon icon-table"></span> Tables </a>') ?>
        <?= Html::link("mango/index", '<span class="icon icon-sitemap"></span> Statistics </a>') ?>
        <?= Html::link("mango/index", '<span class="icon icon-list-alt"></span> Forms </a>') ?>
        <?= Html::link("mango/index", '<span class="icon icon-table"></span> Tables </a>') ?>
        <?= Html::link("mango/index", '<span class="icon icon-table"></span> Tables </a>') ?>
    </div><!-- End of .buttons -->
</header><!-- End of header -->