<!-- The header containing the logo -->
<header class="container_12">
    <!-- Your logos -->
    <?= Load::lib("html"); ?>
    <?= Html::link("mango/index", Html::imagen("logo.png","Mango",191,60)) ?>
    <?= Html::link("mango/index",Html::imagen("logo-mobile.png","Mango",22,70),"class: phone-title") ?>

    <div class="buttons">
        <?= Html::linkAjax("menu/x", '<span class="icon icon-sitemap"></span> Statistics',"tmpx") ?>
        <?= Html::link("mango/index", '<span class="icon icon-list-alt"></span> Forms') ?>
        <?= Html::link("mango/index", '<span class="icon icon-table"></span> Tables') ?>
        <?= Html::link("mango/index", '<span class="icon icon-sitemap"></span> Statistics') ?>
        <?= Html::link("mango/index", '<span class="icon icon-list-alt"></span> Forms') ?>
        <?= Html::link("mango/index", '<span class="icon icon-table"></span> Tables') ?>
        <?= Html::link("mango/index", '<span class="icon icon-table"></span> Tables') ?>
    </div><!-- End of .buttons -->
</header><!-- End of header -->