<!-- The sidebar -->
<aside>
	<div class="top">

		<!-- Navigation -->
		<nav>
			<ul class="collapsible accordion">
				<li>
					<?= Html::link("mango/index", Html::imagen("icons/packs/fugue/16x16/dashboard.png","",16,16).utf8_encode("Dashboard")) ?>
				</li>
				<li>
					<?= Html::link("javascript:void(0);", Html::imagen("icons/packs/fugue/16x16/ui-layered-pane.png","",16,16).utf8_encode('UI Widgets<span class="badge">4</span>')) ?>
					<ul>
						<li>
							<a href="ui_general.html"><span class="icon icon-list"></span>General</a>
						</li>
						<li>
							<a href="ui_extras.html"><span class="icon icon-cog"></span>Extras</a>
						</li>
						<li>
							<a href="ui_icons.html"><span class="icon icon-picture"></span>Icons</a>
						</li>
						<li>
							<a href="ui_grid.html"><span class="icon icon-th"></span>Grid</a>
						</li>
					</ul>
				</li>

				<li>
					<a class="open" href="javascript:void(0);"><img src="img/icons/packs/fugue/16x16/application-form.png" alt="" height=16 width=16>Form Elements</a>
					<ul>
						<li class="current">
							<a href="forms.html"><span class="icon icon-list-alt"></span>General</a>
						</li>
						<li>
							<a href="forms_validation.html"><span class="icon icon-warning-sign"></span>Validation</a>
						</li>
						<li>
							<a href="forms_extras.html"><span class="icon icon-magic"></span>Fileuploader &amp; Wizard</a>
						</li>
					</ul>
				</li>

				<li>
					<a href="javascript:void(0);"><img src="img/icons/packs/fugue/16x16/chart.png" alt="" height=16 width=16>Statistics / Charts<span class="badge">2</span></a>
					<ul>
						<li>
							<a href="statistics.html"><span class="icon icon-sitemap"></span>Statistics Elements</a>
						</li>
						<li>
							<a href="charts.html"><span class="icon icon-bar-chart"></span>Charts</a>
						</li>
					</ul>
				</li>

				<li>
					<a href="javascript:void(0);"><img src="img/icons/packs/fugue/16x16/table.png" alt="" height=16 width=16>Tables</a>
					<ul>
						<li>
							<a href="tables_static.html"><span class="icon icon-check-empty"></span>Static</a>
						</li>
						<li>
							<a href="tables_dynamic.html"><span class="icon icon-table"></span>Dynamic</a>
						</li>
						<li>
							<a href="tables_full.html"><span class="icon icon-fullscreen"></span>Full</a>
						</li>
					</ul>
				</li>

				<li>
					<a href="javascript:void(0);"><img src="img/icons/packs/fugue/16x16/document-horizontal.png" alt="" height=16 width=16>Other Pages</a>
					<ul>
						<li>
							<a href="login.html">Login</a>
						</li>
						<li>
							<a href="pages_profile.html">Profile</a>
						</li>
						<li>
							<a href="pages_invoice.html">Invoice<span class="badge grey">1 open</span></a>
						</li>
						<li>
							<a href="pages_faq.html">FAQ</a>
						</li>
						<li>
							<a href="pages_search.html">Search</a>
						</li>
						<li>
							<a href="pages_error_404.html">Error Page (404)</a>
						</li>
					</ul>
				</li>

			</ul>
		</nav><!-- End of nav -->
	</div><!-- End of .top -->

	<div class="bottom sticky">
		<div class="divider"></div>
		<div class="progress">
			<div class="bar" data-title="Space" data-value="1285" data-max="5120" data-format="0,0 MB"></div>
			<div class="bar" data-title="Traffic" data-value="8.61" data-max="14" data-format="0.00 GB"></div>
			<div class="bar" data-title="Budget" data-value="20000" data-max="20000" data-format="$0,0"></div>
		</div>
		<div class="divider"></div>
		<div class="buttons">
			<a href="javascript:void(0);" class="button grey open-add-client-dialog">Add New Client</a>
			<a href="javascript:void(0);" class="button grey open-add-client-dialog">Open a Ticket</a>
		</div>
	</div><!-- End of .bottom -->

</aside><!-- End of sidebar -->