<!-- The blue toolbar stripe -->
<section class="toolbar">
	<div class="user">
		<div class="avatar">
			<?= Html::imagen("layout/content/toolbar/user/avatar.png") ?>
			<!-- <span>7</span> -->
		</div>
		<span>Configuraci&oacute;n</span>
		<ul>
			<li>
				<?= Html::link("javascript:$$.settings();", "General") ?>
			</li>
			<li class="line"></li>
			<li>
				<?= Html::link("mango/index", "Unidades") ?>
			</li>
			<li>
				<?= Html::link("mango/index", "Impuestos") ?>
			</li>
			<li>
				<?= Html::link("mango/index", "Monedas") ?>
			</li>
			<li class="line"></li>
			<li>
				<?= Html::link("mango/index", "Usuarios") ?>
			</li>
			<li>
				<?= Html::linkAjax("roles/index", "Roles","contenido") ?>
			</li>
			<li class="line"></li>
			<li>
				<?= Html::link("mango/index", "Facturaci&oacute;n Electr&oacute;nica") ?>
			</li>
			<li class="line"></li>
			<li>
				<?= Html::link("logout", "Cerrar Sesi&oacute;n") ?>
			</li>
		</ul>
	</div>
	<ul class="shortcuts">
		<li>
			<?= Html::link("javascript:void(0);", '<span class="icon i24_user-business"></span>') ?>
			<!-- Possible sizes: small/medium/large -->
			<div class="small">
				<h3>Nuevo Usuario</h3>

				<!-- Button bar -->
				<button class="button flat left grey" onclick="$(this).parent().fadeToggle($$.config.fxSpeed).parent().removeClass('active')">
					Cerrar
				</button>
				<button class="button flat right" onclick="$(this).parent().fadeToggle($$.config.fxSpeed).parent().removeClass('active')">
					Nuevo
				</button>

				<div class="content">
					<?= Formulario::inicio("",0,"class: full grid") ?>
						<div class="row no-bg">
							<p class="_100 small">
								<label for="p1_username">Usuario</label>
								<?= Formulario::texto("p1_username") ?>
							</p>
						</div>
						<div class="row no-bg">
							<p class="_50 small">
								<label for="p1_firstname">Nombre(s)</label>
								<?= Formulario::texto("p1_firstname") ?>
							</p>
							<p class="_50 small">
								<label for="p1_lastname">Apellidos</label>
								<?= Formulario::texto("p1_lastname") ?>
							</p>
						</div>
					<?= Formulario::fin() ?>
				</div>
			</div><!-- End of popup -->
		</li>

		<li>
			<?= Html::link("javascript:void(0);", '<span class="icon i24_inbox-document"></span>') ?>
			<!-- Possible sizes: small/medium/large -->
			<div class="small">
				<h3>Enviar Mensaje</h3>

				<!-- Button bar -->
				<button class="button flat left grey" onclick="$(this).parent().fadeToggle($$.config.fxSpeed).parent().removeClass('active')">
					Cerrar
				</button>
				<button class="button flat right" onclick="$(this).parent().fadeToggle($$.config.fxSpeed).parent().removeClass('active')">
					Enviar
				</button>

				<div class="content">
					<?= Formulario::inicio("",0,"class: full grid") ?>
						<div class="row no-bg">
							<p class="_100 small">
								<?= Formulario::texto("p1_lastname","","placeholder: Destinatario") ?>
							</p>
							<p class="_100 small">
								<?= Formulario::texto("p1_lastname","","placeholder: Asunto") ?>
							</p>
							<p class="_100 small">
								<?= Formulario::textarea("p2_message","","rows: 5","style: overflow: hidden; height: 45px; width: 100%; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; -ms-box-sizing: border-box; box-sizing: border-box;","placeholder: Mensaje") ?>
							</p>
						</div>
					<?= Formulario::fin() ?>
				</div>
			</div><!-- End of popup -->
		</li>

		<li>
			<?= Html::link("javascript:void(0);", '<span class="icon i24_application-blue"></span>') ?>
			<!-- Possible sizes: small/medium/large -->
			<div class="small">
				<h3>Informaci&oacute;n</h3>

				<!-- Button bar -->
				<button class="button flat left grey" onclick="$(this).parent().fadeToggle($$.config.fxSpeed).parent().removeClass('active')">
					Cerrar
				</button>

				<div class="content">
					<p>
						Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
					</p>
				</div>
			</div><!-- End of popup -->
		</li>

	</ul><!-- End of .shortcuts -->

	<input type="search" data-source="extras/search.php" placeholder="Buscar..." autocomplete="off" class="tooltip" title="Ingresa palabra de busqueda" data-gravity=s>
</section><!-- End of .toolbar-->